package com.stu.dormitory.modules.application.enums;

public enum PriorityDocumentType {
    POVERTY_CERTIFICATE,
    MARTYR_CERTIFICATE,
    WOUNDED_SOLDIER_CERTIFICATE,
    ETHNIC_CERTIFICATE,
    DISABILITY_CERTIFICATE,
    ORPHAN_CERTIFICATE,
    REMOTE_AREA_CERTIFICATE,
    PARTY_MEMBER_CERTIFICATE
}