spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/dormitory_db
    username: postgres
    password: 19052004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

brevo:
  api-key: ${BREVO_API_KEY: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}
  sender-email: quoctinhstudy1911@gmail.com
  sender-name: Dormitory System

jwt:
  access-secret: "z8Xp2wR5vA9nL4kQ7jH1mS4tC6fG9hJ2kL5mR7QjW1xY4tA6sD9fG0hJ2kL5mR7Q"
  refresh-secret: "b3V8M1qP9nL5mR7QjW1xY4tA6sD9fG0hJ2kL5mR7QjW1xY4tA6sD9fG0hJ2kL5m"
  access-expiration: 900000
  refresh-expiration: 604800000

cloudinary:
  cloud-name: dpds3gjbj
  api-key: 261367755435666
  api-secret: KusiaJcJfXcevGQe0w45_E6UKxk

server:
  port: 8080

logging:
  level:
    com.stu.dormitory: DEBUG